### ISSUE TITLE
Eittris rocks!

### ISSUE THREAD

**Issue by raptor** [nebosite/groundup#1]
I played eittris not 5 years ago with my brother crammed on a laptop running a VM.

I saw some links talking about a Microsoft XNA version `eitrix` but links seem dead. I found a version on archive.org from 2016 and tried it. Is this game still being developed? Could I contribute to it (esp. adding more joystick support)?

**Comment by nebosite** [comment]
Hi @raptor !   I finally got around today to creating a repo for the latest code.   I haven't touched it for years, and you are more than welcome to fork it and start jamming on the code!  

https://github.com/nebosite/eittrix

PS:  I'm going to try to get it compiling on vs2019 today.   If you don't see any new checkins from me today, I'll probably not have time to get it compiling, so that would be a good first project. ;)

**Comment by nebosite** [comment]
@raptor - New link: https://github.com/nebosite/eitrix

I've got it compiling, but it crashes because it's not compiling any content.   Probably a simple fix, but I don't have time  to mess with it.   Check the readme.md file for infor on how to get dev env set up.

**Comment by raptor** [comment]
Thanks! I got to the same point and I'm fixing paths.
